// NativeWind/tailwind-aware CSS registry regeneration.
//
// On native, className styling works through ONE compiled registry module in the
// bundle (react-native-css-interop/.cache/<platform>.js -> injectData({...})),
// generated by tailwind FROM THE SOURCE TREE AT BUILD TIME. A baked image compiled
// it from the template scaffold, so classes used only by files added later (every
// AI-generated screen) simply don't exist in it — components render UNSTYLED even
// though their modules hot-load fine. This module re-runs the same pipeline
// nativewind's metro integration uses (its tailwind child process one-shot ->
// cssToReactNativeRuntime -> injectData source) so the thin server can push and
// patch a fresh registry whenever the source tree drifts.
import { fork } from 'node:child_process'
import crypto from 'node:crypto'
import fs from 'node:fs'
import path from 'node:path'
import { createRequire } from 'node:module'

// The css input file withNativeWind was configured with. Parsing the metro config as
// text is deliberate — requiring it would boot the whole expo/metro config stack.
export function cssInputPath(projectDir) {
  try {
    const cfg = fs.readFileSync(path.join(projectDir, 'metro.config.js'), 'utf8')
    const m = cfg.match(/input:\s*['"]([^'"]+)['"]/)
    if (m) return path.resolve(projectDir, m[1])
  } catch {}
  for (const c of ['global.css', 'src/global.css', 'app/global.css']) {
    const p = path.join(projectDir, c)
    if (fs.existsSync(p)) return p
  }
  return null
}

export function isNativeWindProject(projectDir) {
  const req = createRequire(projectDir + '/')
  try { req.resolve('nativewind/dist/metro/tailwind/v3/child.js'); return !!cssInputPath(projectDir) } catch { return false }
}

// One-shot tailwind run (the same child nativewind forks, without watch): resolves
// with the compiled CSS for the platform. cwd matters — the tailwind content globs
// are relative to the project.
function tailwindCss(projectDir, platform, input) {
  const req = createRequire(projectDir + '/')
  const child_file = req.resolve('nativewind/dist/metro/tailwind/v3/child.js')
  return new Promise((resolve, reject) => {
    const child = fork(child_file, {
      cwd: projectDir,
      stdio: 'pipe',
      env: {
        ...process.env,
        NATIVEWIND_INPUT: input,
        NATIVEWIND_OS: platform,
        NATIVEWIND_WATCH: 'false',
        BROWSERSLIST: 'last 1 version',
        BROWSERSLIST_ENV: 'native',
      },
    })
    const t = setTimeout(() => { try { child.kill() } catch {} ; reject(new Error('tailwind timed out (60s)')) }, 60_000)
    let done = false
    child.on('message', (msg) => { if (!done) { done = true; clearTimeout(t); resolve(String(msg)); try { child.kill() } catch {} } })
    child.on('error', (e) => { clearTimeout(t); reject(e) })
    child.on('exit', (code) => { if (!done) { clearTimeout(t); reject(new Error(`tailwind exited ${code} before emitting css`)) } })
  })
}

// css-interop's cache-file number formatting (getNativeJS rounds to 3 decimals);
// JSON.stringify matches everything else it emits for plain data.
const round3 = (_k, v) => (typeof v === 'number' ? Math.round(v * 1000) / 1000 : v)

// Generate the SOURCE of a fresh registry module for `platform` ('ios'|'android'),
// exactly the shape css-interop's own transformer produces for .cache/<platform>.js.
export async function generateCssModuleSource(projectDir, platform) {
  const req = createRequire(projectDir + '/')
  const input = cssInputPath(projectDir)
  if (!input) throw new Error('no nativewind css input found')
  const css = await tailwindCss(projectDir, platform, input)
  const { cssToReactNativeRuntime } = req('react-native-css-interop/dist/css-to-rn')
  let common = {}
  try { common = req('nativewind/dist/metro/common').cssToReactNativeRuntimeOptions } catch {}
  let selectorPrefix
  try {
    const important = req('tailwindcss/loadConfig')(path.join(projectDir, 'tailwind.config.js')).important
    if (typeof important === 'string') selectorPrefix = important
  } catch {}
  const data = cssToReactNativeRuntime(css, { ...common, inlineRem: 14, selectorPrefix })
  const source = `import { injectData } from "react-native-css-interop/dist/runtime/native/styles";injectData(${JSON.stringify(data, round3)});`
  return { source, hash: crypto.createHash('sha256').update(source).digest('hex') }
}

// The registry module's rel path inside a parsed bundle, if the bake included one.
export function cssCacheModuleRel(maps, platform) {
  const exact = `node_modules/react-native-css-interop/.cache/${platform}.js`
  if (maps.pathToId.has(exact)) return exact
  const native = 'node_modules/react-native-css-interop/.cache/native.js'
  if (maps.pathToId.has(native)) return native
  return null
}
